[package]
name = "rs-uptime-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
signal-hook = "0.3"
users = "0.11"

[[bin]]
name = "boot"
path = "src/boot.rs"

[[bin]]
name = "closedown"
path = "src/closedown.rs"

[[bin]]
name = "wrappers"
path = "src/wrappers.rs"
