[package]
name = "rs-uptime-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
signal-hook = "0.3"

[[bin]]
name = "boot"
path = "src/boot.rs"

[[bin]]
name = "shutdown"
path = "src/shutdown.rs"